name: Webhook Update OpenUchile

on:
  workflow_run:
    workflows:
      - 'Docker Image CI'
    types:
      - completed

jobs:
  webhook:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Trigger argo repository
        run: |
         curl --silent --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/open-uchile/argocd-config/dispatches --data '{"event_type": "update-images-v2", "client_payload": {"type": "openuchile"}}'
