name: Webhook Update staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger second repository
        run: |
          curl -XPOST -u "open-eol:${{ secrets.CR_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/open-uchile/argocd-config/dispatches --data '{"event_type": "update-images", "client_payload": {"type": "openuchile"}}'
